// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCacDcLcTz0cDXW8PtceSTuBvZgpgYkT08',
    appId: '1:909558811761:web:7493402576ffbac8f85fd0',
    messagingSenderId: '909558811761',
    projectId: 'alfred-mkrabs',
    authDomain: 'alfred-mkrabs.firebaseapp.com',
    storageBucket: 'alfred-mkrabs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCET-E1Emy_pI4liO0Os6aLBpc7wNFxpBs',
    appId: '1:909558811761:android:8ccef4287a085b44f85fd0',
    messagingSenderId: '909558811761',
    projectId: 'alfred-mkrabs',
    storageBucket: 'alfred-mkrabs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWh7Ymnbe7JUyu681In-vUBSA5lqHhzE',
    appId: '1:909558811761:ios:8563e33ec94e2cc2f85fd0',
    messagingSenderId: '909558811761',
    projectId: 'alfred-mkrabs',
    storageBucket: 'alfred-mkrabs.appspot.com',
    iosClientId: '909558811761-l1jbkpu9hpnre8v9p6bin8bsmk93qjrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.alfred',
  );
}
